# Attendence

In [1]:
import numpy as np
import pandas as pd
import re

In [15]:
x = """
Tabish sheikh3:01 PM
Thank you sir aj to maza arha h full motivational session
Syed Muhammad Abdullah3:02 PM
What an inspirational and motivational session it is going thank you sir for these two amazing qoutes.
Muhammad faizan Farooque3:12 PM
I think we have big syllabus to cover in small span of time and we are enjoying motivational quotes :)
Syed Daniyal3:17 PM
Yes yes i know
Muhammad Rohan3:24 PM
Waqas please mute your mic
Munir Ali3:27 PM
Waqas please mute your mic
Muneeb Ahmed3:28 PM
42101-8342718-3
Mohsin Kanani3:29 PM
4230108335683
Muhammad faizan Farooque3:29 PM
4230139663957
zain abidi3:29 PM
4250119167549
Rozina Mazhar Ali3:30 PM
4220159083880
Dewan S Khan3:31 PM
4220105630741 Dewan
Tabish sheikh3:39 PM
4210129511133 - Tabish Ahmed
Syed Muhammad Abdullah3:39 PM
4220122868467
Nazneen Akram3:39 PM
4210145447712
Syed Muhammad Abdullah3:39 PM
syed Muhammad Abdullah
Tariq Mehmood3:39 PM
4220104505899
Malik Humza3:39 PM
4240105171159
Shakir Hussain3:40 PM
4210182767349
Munir Ali3:40 PM
4220101410369
taimoor qureshi3:40 PM
4240179641627
Zahid Bashir3:40 PM
4250191411023
Syed Kashif3:40 PM
4250144488545
HAREEM RIZVI3:40 PM
42101-3311570-4
Syed Tanveer3:40 PM
4220169252467
Dewan S Khan3:40 PM
4220105630741
Yusra Adnan3:40 PM
4210164790696
Shoaib Abdul Razzaque3:41 PM
51401-7679165-1
Waqas Zafar3:41 PM
5440004083505
Zareen Fatima3:42 PM
3520269403788
Arsalan Ahmed3:45 PM
4220165351957
Muhammad Ayaz3:53 PM
4410242997959
Muhammad Rohan3:53 PM
4210116966995
Zeeshan Naqvi3:53 PM
4210151751811
Tabish sheikh3:53 PM
4210129511133
Saba Naz3:53 PM
42501-2598780-8
Muhammad faizan Farooque3:53 PM
4230139662957
zain abidi3:53 PM
4250119167549
Dewan S Khan3:53 PM
4220105630741
Shakir Hussain3:53 PM
4210182767349
Muhammad Atique Qayyum3:53 PM
4220140225263
Syed Ali3:53 PM
42401-1880106-5
Qazi Moawiz3:53 PM
31303-9922122-5
Mohsin Kanani3:53 PM
4230108335683
Ali Naiyar3:53 PM
4210198030681
usman ahmad3:53 PM
4220113316709
Qazi Moawiz3:53 PM
4210156195059
Bilal Ahmed3:53 PM
4210120075463 Imandar Bilal
Khizra Rizvi3:54 PM
5440047459326
Muhammad Sarfraz Moiz3:54 PM
4240151906335
Zeeshan Javed3:54 PM
4230189725317
Mushyada Ali3:54 PM
4210103553847
Fazal Diyan3:54 PM
4230129459921
Bilal Ahmed3:54 PM
424015190633
Sania Tehseen3:54 PM
4210115022744
Syed Sajjad Raxa3:54 PM
42201-4347114-3 .. honesty is the best policy ..
Hassan Khan3:54 PM
4240160019477
Bilal Ahmed3:54 PM
4230129459921
4230129459921
Imandar Fazal
Asima Ali3:54 PM
4420626938874
Ad Khan3:54 PM
Muhammad Adnan Khan
Syed Ammad Waheed3:54 PM
Syed Ammad Waheed Hassani 4210113863591
Wasiq Gt3:55 PM
4250104502069
Ad Khan3:55 PM
Muhammad Adnan Khan
Muhammad Uzair3:55 PM
42101-59264578
Hassan Khan3:55 PM
Hassan Khan
4240160019477
Ad Khan3:55 PM
Muhammad Adnan Khan 4220113823383
manal khan3:55 PM
4210170238438
Afnan Ali3:56 PM
Muhammad Afnan Ali Khan
Sumayya Kamran EB20_125 (EB20102125)3:56 PM
4250106544552
Afnan Ali3:56 PM
Muhammad Afnan ALi Khan 4210146436547
Tabassum Ali3:56 PM
4230123126547
"""
x=x.replace("-","")
print(x)
cnic = pd.DataFrame(list(set(re.findall(r"\b[0-9]{13}\b",x))), columns=["cnic"])
print(len(cnic))

Tabish sheikh3:01 PM
Thank you sir aj to maza arha h full motivational session
Syed Muhammad Abdullah3:02 PM
What an inspirational and motivational session it is going thank you sir for these two amazing qoutes.
Muhammad faizan Farooque3:12 PM
I think we have big syllabus to cover in small span of time and we are enjoying motivational quotes :)
Syed Daniyal3:17 PM
Yes yes i know
Muhammad Rohan3:24 PM
Waqas please mute your mic
Munir Ali3:27 PM
Waqas please mute your mic
Muneeb Ahmed3:28 PM
4210183427183
Mohsin Kanani3:29 PM
4230108335683
Muhammad faizan Farooque3:29 PM
4230139663957
zain abidi3:29 PM
4250119167549
Rozina Mazhar Ali3:30 PM
4220159083880
Dewan S Khan3:31 PM
4220105630741 Dewan
Tabish sheikh3:39 PM
4210129511133  Tabish Ahmed
Syed Muhammad Abdullah3:39 PM
4220122868467
Nazneen Akram3:39 PM
4210145447712
Syed Muhammad Abdullah3:39 PM
syed Muhammad Abdullah
Tariq Mehmood3:39 PM
4220104505899
Malik Humza3:39 PM
4240105171159
Shakir Hussain3:40 PM
4210182767349
Munir Ali3:40 PM
4220101410369
taimoor qureshi3:40 PM
4240179641627
Zahid Bashir3:40 PM
4250191411023
Syed Kashif3:40 PM
4250144488545
HAREEM RIZVI3:40 PM
4210133115704
Syed Tanveer3:40 PM
4220169252467
Dewan S Khan3:40 PM
4220105630741
Yusra Adnan3:40 PM
4210164790696
Shoaib Abdul Razzaque3:41 PM
5140176791651
Waqas Zafar3:41 PM
5440004083505
Zareen Fatima3:42 PM
3520269403788
Arsalan Ahmed3:45 PM
4220165351957
Muhammad Ayaz3:53 PM
4410242997959
Muhammad Rohan3:53 PM
4210116966995
Zeeshan Naqvi3:53 PM
4210151751811
Tabish sheikh3:53 PM
4210129511133
Saba Naz3:53 PM
4250125987808
Muhammad faizan Farooque3:53 PM
4230139662957
zain abidi3:53 PM
4250119167549
Dewan S Khan3:53 PM
4220105630741
Shakir Hussain3:53 PM
4210182767349
Muhammad Atique Qayyum3:53 PM
4220140225263
Syed Ali3:53 PM
4240118801065
Qazi Moawiz3:53 PM
3130399221225
Mohsin Kanani3:53 PM
4230108335683
Ali Naiyar3:53 PM
4210198030681
usman ahmad3:53 PM
4220113316709
Qazi Moawiz3:53 PM
4210156195059
Bilal Ahmed3:53 PM
4210120075463 Imandar Bilal
Khizra Rizvi3:54 PM
5440047459326
Muhammad Sarfraz Moiz3:54 PM
4240151906335
Zeeshan Javed3:54 PM
4230189725317
Mushyada Ali3:54 PM
4210103553847
Fazal Diyan3:54 PM
4230129459921
Bilal Ahmed3:54 PM
424015190633
Sania Tehseen3:54 PM
4210115022744
Syed Sajjad Raxa3:54 PM
4220143471143 .. honesty is the best policy ..
Hassan Khan3:54 PM
4240160019477
Bilal Ahmed3:54 PM
4230129459921
4230129459921
Imandar Fazal
Asima Ali3:54 PM
4420626938874
Ad Khan3:54 PM
Muhammad Adnan Khan
Syed Ammad Waheed3:54 PM
Syed Ammad Waheed Hassani 4210113863591
Wasiq Gt3:55 PM
4250104502069
Ad Khan3:55 PM
Muhammad Adnan Khan
Muhammad Uzair3:55 PM
4210159264578
Hassan Khan3:55 PM
Hassan Khan
4240160019477
Ad Khan3:55 PM
Muhammad Adnan Khan 4220113823383
manal khan3:55 PM
4210170238438
Afnan Ali3:56 PM
Muhammad Afnan Ali Khan
Sumayya Kamran EB20_125 (EB20102125)3:56 PM
4250106544552
Afnan Ali3:56 PM
Muhammad Afnan ALi Khan 4210146436547
Tabassum Ali3:56 PM
4230123126547

52

In [17]:
cnic = pd.DataFrame(list(set(re.findall(r"\b[0-9]{13}\b",x))), columns=["cnic"])
print(len(cnic))
#cnic = list(set(cnic))
#print(len(cnic))
cnic

52

             cnic
0   4250144488545
1   4210133115704
2   4220105630741
3   4220159083880
4   5140176791651
5   3130399221225
6   4220113316709
7   4230108335683
8   4210156195059
9   4250106544552
10  4410242997959
11  4210151751811
12  4210120075463
13  4210113863591
14  4210159264578
15  4230139663957
16  4250119167549
17  4230123126547
18  4210145447712
19  4240105171159
20  4420626938874
21  4220122868467
22  4220101410369
23  3520269403788
24  4210183427183
25  4220140225263
26  4250104502069
27  4240118801065
28  4210129511133
29  4240151906335
30  4210103553847
31  4230139662957
32  4230189725317
33  4220104505899
34  4210115022744
35  4210198030681
36  4220169252467
37  4220165351957
38  4240179641627
39  5440047459326
40  4210146436547
41  5440004083505
42  4210170238438
43  4210164790696
44  4250125987808
45  4230129459921
46  4250191411023
47  4220113823383
48  4220143471143
49  4240160019477
50  4210182767349
51  4210116966995

In [21]:
import pandas as pd
df.to_excel("class1_attendance.xlsx",index=False)

NameError: name 'df' is not defined